[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["cd training/peft && python -m pip install -r requirements.txt"]

[start]
cmd = "cd training/peft && uvicorn slack_api:app --host 0.0.0.0 --port $PORT"
