[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = ["cd training/peft && pip install -r requirements.txt"]

[start]
cmd = "cd training/peft && uvicorn slack_api:app --host 0.0.0.0 --port $PORT"
